name: Formatting
run-name: Checking formatting of files
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checking with Prettier
        uses: actionsx/prettier@v2
        with:
          args: --check .
